### ISSUE TITLE
Master Development Ticket

### ISSUE THREAD

**Issue by Barrett17** [Barrett17/V-OS#1]
## Roadmap V\OS Alpha1

#### pre-Alpha 2

* ~~Adopt cmake and ninja based buildsystem~~
* ~~Update our codebase to beta1 or later Haiku revision~~
* ~~Introduce fbdev backend for the app_server~~
* ~~Port Deskbar~~
* Tests
* Storage code refactor
* Introduce an input_server addon using libinput
* Port Tracker

#### Alpha Release
* Release for x86, x86_64 and ARM 
* iso image
* Support for building standalone images with the linux kernel included

**Comment by cb88** [comment]
This is just a suggestion, how about not exactly doing an xserver backend but doing it in a portable manner so it builds crossplatform... maybe SDL I think there is some support there for shaped windows and even 2D acceleration at least equivalent to what Haiku implements.

The X server is sort of becoming deprecated anyway these days.

**Comment by Barrett17** [comment]
The reason is that creating an xserver backend should be easier. While I have the app_server running (without backend) it still needs a lot of testing and massaging to become stable. Going with the framebuffer driver directly would be a bit of a jump in the void.

**Comment by Barrett17** [comment]
So, the development is going to restart soon, keep in tune :)

**Comment by Barrett17** [comment]
> This is just a suggestion, how about not exactly doing an xserver backend but doing it in a portable manner so it builds crossplatform... maybe SDL I think there is some support there for shaped windows and even 2D acceleration at least equivalent to what Haiku implements.

Using SDL is sort of interesting. But I'm worried it will pose some hard limits in future, I will investigate...

At the moment I'm focused on the linux framebuffer driver let's see what comes out.

**Comment by Barrett17** [comment]
Both. But before fbdev because it's much more simple. Then libdrm, using DRM framebuffer directly can be done but it's not probably a good idea because needs some hacky stuff.

I don't see it being really deprecated. It is still supported AFAIK.

**Comment by Barrett17** [comment]
The interesting thing of using libdrm is that it's an half-done wayland backend.

**Comment by Barrett17** [comment]
> I don't see it being really deprecated. It is still supported AFAIK.

It turns out you are right, it was in theory deprecated in 2015, but it's still there...
