### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by inuyasha82** [Barrett17/V-OS#14]
FAILED: src/apps/osutils/portinfo 
: && /usr/bin/c++  -include LinuxBuildCompatibility.h -Wall  -Wpointer-arith -Wcast-align -Wsign-compare -Wstrict-aliasing  -Wno-multichar -fPIC -fdiagnostics-color  -Woverloaded-virtual -Wno-ctor-dtor-privacy  -Wnon-virtual-dtor -fexceptions -fpermissive   src/apps/osutils/CMakeFiles/portinfo.dir/portinfo.cpp.o  -o src/apps/osutils/portinfo -L/home/vetinari/Projects/vos/V-OS/generated.x86/external/icu-cmake/icu_host/lib -Wl,-rpath,/home/vetinari/Projects/vos/V-OS/generated.x86/src/kits:/home/vetinari/Projects/vos/V-OS/generated.x86/src/system:/home/vetinari/Projects/vos/V-OS/generated.x86/external/icu-cmake/icu_host/lib src/kits/libbe.so src/system/libroot.so -ldl -lpthread /usr/lib/x86_64-linux-gnu/libz.so -lrt src/libs/linprog/liblinprog.a src/libs/icon/libicon.a src/libs/agg/libagg.a -licudata -licui18n -licuio -licutu -licuuc && :
src/system/libroot.so: undefined reference to `BLocker::Unlock()'
src/system/libroot.so: undefined reference to `BList::_ReservedList2()'
src/system/libroot.so: undefined reference to `BList::operator=(BList const&)'
src/system/libroot.so: undefined reference to `_PointerList_::ReplaceItem(int, void*)'
src/system/libroot.so: undefined reference to `BList::AddItem(void*)'
src/system/libroot.so: undefined reference to `typeinfo for _PointerList_'
src/system/libroot.so: undefined reference to `BLocker::~BLocker()'
src/system/libroot.so: undefined reference to `BString::BString(char const*)'
src/system/libroot.so: undefined reference to `BString::BString(BString const&)'
src/system/libroot.so: undefined reference to `BList::ItemAt(int) const'
src/system/libroot.so: undefined reference to `BList::CountItems() const'
src/system/libroot.so: undefined reference to `BLocker::BLocker()'
src/system/libroot.so: undefined reference to `_PointerList_::_PointerList_(int, bool)'
src/system/libroot.so: undefined reference to `BList::MakeEmpty()'
src/system/libroot.so: undefined reference to `BString::~BString()'
src/system/libroot.so: undefined reference to `BList::_ReservedList1()'
src/system/libroot.so: undefined reference to `BLocker::Lock()'
src/system/libroot.so: undefined reference to `_PointerList_::~_PointerList_()'
collect2: error: ld returned 1 exit status
[721/788] Building CXX object src/apps/pairs/CMakeFiles/Pairs.dir/PairsWindow.cpp.o
ninja: build stopped: subcommand failed.

**Comment by inuyasha82** [comment]
Fixed in development.

**Comment by Barrett17** [comment]
Fixed at 26364192048a7660a814b2994715db5e4366b866
