### ISSUE TITLE
Investigate possible solutions for package management

### ISSUE THREAD

**Issue by Barrett17** [Barrett17/V-OS#18]
At some point we want to ship the Operating System with a package management solution. This probably don't have any priority before the system is usable. Rather than implementing a new package management solution, using an existing one make much more sense. Possible candidates includes:

* apt
* nix
...

This ticket is due before the stable release.

**Comment by embeddedden** [comment]
Hi, I am really glad that you project is growing. I am also working on my project and now have currently the same task: https://medium.com/@denisobrezkov/colossus-work-report-6-looking-for-an-ideal-package-manager-planning-phase-1c131eb91590
In few maybe I will be able to produce some interesting results.

**Comment by Barrett17** [comment]
Great to see you around! Your research looks interesting for us, will follow definitely.
