### ISSUE TITLE
Add more information into Readme file.

### ISSUE THREAD

**Issue by inuyasha82** [Barrett17/V-OS#4]
I think that more information should be added to help new users/contributors: 

1.  I think a prerequisite section should be added highlighting all packages/configuration needed for building and running this project
2. Also add a section explaining how to run it (because once built not everyone knows what to do to use it. 
3. Maybe add one or two screenshot?

**Comment by Barrett17** [comment]
Screenshots need to wait IMHO. I think we should add some docs subdirectory probably to document various things, including API changes and incompatibilities from BeOS/Haiku.

**Comment by inuyasha82** [comment]
Yeah sure, but in the README we should at least specify dependencies and how to use. 

So far the dependencies you probably need to install are: 

- cmake
- Ninja 

at least on my linux machine.

**Comment by inuyasha82** [comment]
another dependency that needs to be added: 

libinput-dev

**Comment by inuyasha82** [comment]
Another requirements to add is gcc8!

**Comment by inuyasha82** [comment]
I think another information that should be added is how to actually launch it, where to grab needed resources, etc.

**Comment by Barrett17** [comment]
Of course we will. But at the moment such documentation would change a lot of times before becoming definitive. In future this will not be the way to run the system. So I'd like to focus on stuff that's useful long term.

**Comment by Barrett17** [comment]
Fixed. Thanks!
